package com.cypher.breadmote;

import java.util.Date;

/**
 * Represents an error generated by the hardware or by the BreadMote SDK.
 */
public class Error {
    private final String tag;
    private final String message;
    private final Date timeStamp;

    /**
     * @param tag Used to identify the source of the error
     * @param message The reason for the error.
     */
    public Error(String tag, String message) {
        this.tag = tag;
        this.message = message;
        this.timeStamp = new Date();
    }

    /**
     *
     * @return The time this error was created.
     */
    public Date getTimeStamp() {
        return timeStamp;
    }

    /**
     *
     * @return The source of the error
     */
    public String getTag() {
        return tag;
    }

    /**
     * @return The reason for the error
     */
    public String getMessage() {
        return message;
    }
}
